name: PlatformInnova
main: studio.innovacreation.dev.Platform.Platform
version: 0.1

author: bobcao3
commands:
  PullWL:
    description: This will pull White List from server
    usage: /PullWL
    permission: PlatformInnova.basic
    permission-message: You can't access PlatformInnova

  wb:
    description: Open a virtual workbench
    usage: /wb
    permission: PlatformInnova.virtual_wb
    permission-message: You can't access virtual workbench

  enchantment:
    description: Open a virtual enchantment table
    usage: /enchantment
    permission: PlatformInnova.virtual_enchantment
    permission-message: You can't access virtual enchantment table