name: PlatformInnova
main: studio.innovacreation.dev.Platform.Platform
version: 0.1

author: bobcao3
commands:
  PullWL:
    description: This will pull White List from server
    usage: /PullWL
    permission: PlatformInnova.basic
    permission-message: You can't access PlatformInnova

  wb:
    description: Open a virtual workbench
    usage: /wb
    permission: PlatformInnova.virtual_wb
    permission-message: You can't access virtual workbench

  enchantment:
    description: Open a virtual enchantment table
    usage: /enchantment
    permission: PlatformInnova.virtual_enchantment
    permission-message: You can't access virtual enchantment table

  createInstance:
    description: Create a Console Script instance for the command sender
    usage: /createInstance
    permission: ConsoleSripts.createInstance
    permission-message: You can't create an instance of Console Script

  listInstance:
    description: List Console Script instances for the command sender
    usage: /listInstance
    permission: ConsoleSripts.listInstance
    permission-message: You can't list instances of the command sender

  selectInstance:
    description: Select an instance from the instance list as current
    usage: /selectInstance [i]
    permission: ConsoleSripts.selectInstance
    permission-message: You can't select instances from the command sender

  removeSelectedInstance:
    description: Remove the selected instance from the instance list
    usage: /removeSelectedInstance
    permission: ConsoleSripts.removeSelectedInstance
    permission-message: You can't remove instances from the command sender

  eval:
    description: Evaluate the script statement using selected instance of Console Script
    usage: /eval "Statement"
    permission: ConsoleScripts.eval
    permission-message: You don't have the permission to evaluate scripts.