name: PlatformInnova
main: studio.innovacreation.dev.Platform.Platform
version: 0.1

author: bobcao3
commands:
  PullWL:
    description: This will pull White List from server
    usage: /PullWL
    permission: PlatformInnova.basic
    permission-message: You can't access PlatformInnova

author: bobcao3
commands:
  wb:
    description: Open a workbench
    usage: /wb
    permission: PlatformInnova.virtual_wb
    permission-message: You can't access virtual workbench